name: 楽天トウシルのRSSを更新

on:
  workflow_dispatch:
  schedule:
    # 毎日 10:00 (UST) = 19:00 (JST) に実行
    - cron: '0 10 * * *'
    # 毎日 22:00 (UST) = 7:00 (JST) に実行
    - cron: '0 22 * * *'

jobs:
  create-release:
    name: Scraping
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up a Python environment
        uses: actions/setup-python@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests feedgen pytz selenium

      - name: Update toushiru/toushiru.xml
        env:
          LINE_POST_API_URL: ${{ secrets.LINE_POST_API_URL }}
          LINE_POST_TOKEN: ${{ secrets.LINE_POST_TOKEN }}
        run: |
          cd toushiru
          python3 main.py

      - name: Push updates
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          if (git diff --shortstat | grep '[0-9]'); then \
            git add .; \
            git commit -m "`TZ=JST-9 date '+%Y-%m-%dT%H:%M'`更新"; \
            git push origin HEAD:${GITHUB_REF}; \
          fi
